// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "11ce25e8-f537-4a22-b6df-294f52d2b638";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTempChange();
void onGyroXChange();
void onGyroYChange();
void onGyroZChange();

CloudTemperatureSensor temp;
CloudVelocity gyroX;
CloudVelocity gyroY;
CloudVelocity gyroZ;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange, 1);
  ArduinoCloud.addProperty(gyroX, READWRITE, ON_CHANGE, onGyroXChange);
  ArduinoCloud.addProperty(gyroY, READWRITE, ON_CHANGE, onGyroYChange);
  ArduinoCloud.addProperty(gyroZ, READWRITE, ON_CHANGE, onGyroZChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
